### ISSUE TITLE
Improve Documentation on kkpctl 

### ISSUE THREAD

**Issue by cedi** [cedi/kkpctl#11]
The current documentation below `/docs` is only the bare minimum and more meant to be a concept of how the kkpctl cli is supposed to work.
This needs to be documented better

**Comment by lindtdev** [comment]
Hi, I've been writing an article on kkpctl for the Kubermatic blog, I'd be happy to help with some documentation issues I've run into.

**Comment by cedi** [comment]
Hi @lindtdev,

thanks a lot for your interest.
That sounds like an awesome thing to do.
Can I somehow support you, maybe proof read the blog post or something? 

If you need any help, feel free to reach out to me. You can also message me directly on the CNCF Slack @cedi (U019QKK9K7A)

**Comment by lindtdev** [comment]
Hi @cedi that would be awesome!! I will contact you soon with my draft :)
