### ISSUE TITLE
`make install_release` copies the kkpctl binary in place of the bin directory instead of into the bin directory

### ISSUE THREAD

**Issue by lindtdev** [cedi/kkpctl#21]
**Describe the bug**
`make install_release` copies the kkpctl binary in place of the bin directory instead of into the bin directory. As a result there is no bin directory anymore and the binary is not found in $PATH.

**To Reproduce**
Install kkpctl as outlined in the intro guide.

**Desktop (please complete the following information):**
 - OS: tested on both MacOS Big Sur and Ubuntu inside VirtualBox

**Additional context**
It should be enough to just add a / at the end of the build command.

**Comment by cedi** [comment]
Hey @lindtdev,

thanks for the good catch.
This should have been an obvious issue. Thanks for pointing that out!

For some reason on my macOS (BugSur with zsh) it always worked, maybe zsh did some magic that prevented me from overwriting my `$GOPATH/bin` directory.

Would you mind having a look at #22? This should fix the issue

**Comment by lindtdev** [comment]
Thank you, I will take a look at it shortly!
