### ISSUE TITLE
get infos from clusterid only

### ISSUE THREAD

**Issue by qeqar** [cedi/kkpctl#28]
**Is your feature request related to a problem? Please describe.**

As a Kubermatic Operator i mostly get only the Cluster ID and need to search for project ID and Seed Cluster.
My currently on valid option is tu use kubectl an manually search every seed cluster for the cluster.

**Describe the solution you'd like**

I would like to have a search by cluster id function, to get as much infos as possible

**Describe alternatives you've considered**

I already wrote a small bash script tailored to my setup, but needs to be looked into evertytime we change something

**Additional context**

The Kubermatic API is the only merged info about all master/seed resources

**Comment by cedi** [comment]
@qeqar could you have a look at #29 (respective MR #30) which adds the ProjectID to the output of `get cluster`.
Does this already help your use case, or do you need more?

**Comment by qeqar** [comment]
Perfect. the rest is easily done via grep.
